{'weight_decay': 0, 'run_no': 1, 'save_dir': 'save_temp', 'save_every': 5, 'biased': False, 'level': 32, 'compress': False, 'device': 0, 'workers': 4, 'port': '29500', 'method': 'svd', 'skew': 0.0, 'n_clients': 1, 'frac': 1, 'momentum': 0.0, 'increment_th': 0.001, 'lr': 0.01, 'batch_size': 64, 'deterministic': True, 'arch': 'alexnet', 'dataset': 'cifar100', 'classes': 100, 'num_tasks': 10, 'print_times': 5, 'wandb': True, 'gpmflag': True, 'seed': 1234, 'local_epochs': 30, 'buffer_size': 6000, 'alpha': 0.6}
Number of GPU available:  1
Files already downloaded and verified
Files already downloaded and verified
Data partition_sizes among clients: [1.0]
rank 0's total num of datasample in task0:  5056
Epoch: 0, Task: 0, Avg train Loss: 2.0870
Epoch: 1, Task: 0, Avg train Loss: 1.7792
Epoch: 2, Task: 0, Avg train Loss: 1.6381
Epoch: 3, Task: 0, Avg train Loss: 1.5590
Epoch: 4, Task: 0, Avg train Loss: 1.4716
Traceback (most recent call last):
  File "fdr_single.py", line 1005, in <module>
    precision, current_loss, current_acc = client.validate_seen_tasks()
AttributeError: 'Client' object has no attribute 'validate_seen_tasks'
Traceback (most recent call last):
  File "fdr_single.py", line 1005, in <module>
    precision, current_loss, current_acc = client.validate_seen_tasks()
AttributeError: 'Client' object has no attribute 'validate_seen_tasks'
